### ISSUE TITLE
constants.py is missing 

### ISSUE THREAD

**Issue by hyun95roh** [AdrianBZG/llama-multimodal-vqa#4]
According to readme, this is the code for training: 
```
(llama3-ft) python train.py --dataset_path path/to/dataset.json --output_dir path/to/output_dir --text_model_id="meta-llama/Meta-Llama-3-8B-Instruct" --vision_model_id="openai/clip-vit-large-patch14" --batch_size 32
```

I ran the code above on my _**llama3-ft**_ conda env (I changed my path indeed) but I met an error. 
Here is the error message: 
```
Traceback (most recent call last):
  File "C:\Users\nht95\OneDrive\Python\VScode\llama-multimodal-vqa\src\train.py", line 12, in <module>
    from dataset.data_handling import create_dataset
  File "C:\Users\nht95\OneDrive\Python\VScode\llama-multimodal-vqa\src\dataset\data_handling.py", line 1, in <module>
    from dataset.data_classes import SupervisedDataset, DataCollatorForSupervisedDataset
  File "C:\Users\nht95\OneDrive\Python\VScode\llama-multimodal-vqa\src\dataset\data_classes.py", line 11, in <module>
    from dataset.data_utils import preprocess_multimodal
  File "C:\Users\nht95\OneDrive\Python\VScode\llama-multimodal-vqa\src\dataset\data_utils.py", line 8, in <module>
    from constants import IGNORE_INDEX, IMAGE_TOKEN, PAD_TOKEN
ModuleNotFoundError: No module named 'constants'
```

Even after installing constants.py through pip install constants, the error message occurs: 
```
Traceback (most recent call last):
  File "C:\Users\nht95\OneDrive\Python\VScode\llama-multimodal-vqa\src\train.py", line 12, in <module>
    from dataset.data_handling import create_dataset
  File "C:\Users\nht95\OneDrive\Python\VScode\llama-multimodal-vqa\src\dataset\data_handling.py", line 1, in <module>
    from dataset.data_classes import SupervisedDataset, DataCollatorForSupervisedDataset
  File "C:\Users\nht95\OneDrive\Python\VScode\llama-multimodal-vqa\src\dataset\data_classes.py", line 10, in <module>
    from constants import IGNORE_INDEX
ImportError: cannot import name 'IGNORE_INDEX' from 'constants' (C:\Users\nht95\anaconda3\envs\llama3-ft\Lib\site-packages\constants.py)
```

------
On top of that I also found out that this module cannot be found. 
```
from llava_conversation_lib import conv_templates, SeparatorStyle
```

**Comment by SriPrarabdha** [comment]
@hyun95roh these files are present in src/utils folder so in order to fix this issue simply modify
line 10 in src/dataset/data_classes.py to :
`from utils.constants import IGNORE_INDEX`

line 8,9 in src/dataset/data_utils.py to : 
`from utils.constants import IGNORE_INDEX, IMAGE_TOKEN, PAD_TOKEN`
`from utils.llava_conversation_lib import conv_templates, SeparatorStyle`

and finally at line 3 in src/model/configuration_llama.py to :
`from utils.constants import LORA_CONFIG`

**Comment by AdrianBZG** [comment]
Thank you @SriPrarabdha - do you want to open a PR to add these fixes?
